liip_imagine:
    driver: "gd"

    twig:
      mode: 'lazy'

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: /media/cache

    filter_sets:
      images_galery:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [350, 700]
            mode: outbound

      images_architecture_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 500]
            mode: outbound

      images_design_texture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [100, 100]
            mode: outbound

      images_design_plan:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 500]
            mode: outbound

      images_design_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 500]
            mode: outbound

      cache: ~