liip_imagine:
    driver: "gd"

    twig:
      mode: 'lazy'

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: /media/cache

    filter_sets:
      # Filtre page Acueil (galerie)
      images_galery:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [525, 700]
            mode: outbound
      # Filtre modal(galerie) Page Accueil 
      images_modal_galery:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [1200, 900]
            mode: inset

      # Filtre pour les img dans Boursault, Gentilly et Sceaux
      images_architecture_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [700, 900]
            mode: outbound

      # page Tudeils
      # Filtre pour desktop img principal page Tudeils
      image_desktop_tudeils:
        cache: default
        quality: 85
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [1024, 730]
            mode: outbound

      # Filtre pour mobile img principal page Tudeils      
      image_mobile_tudeils:
        quality: 85
        filters:
          strip: ~
          thumbnail:  
            size: [768, 548], 
            mode: outbound 

      # Filtre pour desktop img galerie page Tudeils
      images_gallery_desktop_tudeils:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [500, 666]
            mode: outbound
      # Filtre pour mobile img galerie page Tudeils
      images_gallery_mobile_tudeils:
        cache: default
        quality: 90
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 500] # Tamaño cuadrado para ajustarse al contenedor
            mode: outbound       # Puedes usar 'inset' para asegurar que se recorte y ajuste bien
      #end page Tudeils
      
      # Filtre pour les img texture dans Bureau I et Bureau II
      images_design_texture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [250, 500]
            mode: inset
      # Filtre pour les plan dans Bureau I et Bureau II et SareLight
      images_design_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [1400, 860]
            mode: outbound

      # Filtre pour img Page Contact
      image_contact:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 530]
            mode: inset

      # Filtre pour img Page Sareelight
      image_sareelight:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [996, 1533]
            mode: inset

      # Filtre pour imgs Page Design
      images_accueil_design:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [300, 300]
            mode: outbound

      # Filtre pour imgs Page Design
      images_accueil_architecture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [300, 300]
            mode: outbound

      # Filtre pour imgs Page illustration
      images_illustration:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [591, 591]
            mode: outbound

      # Filtre pour logo Header
      image_logo:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [164, 61]
            mode: inset
      cache: ~