liip_imagine:
    driver: "gd"

    twig:
      mode: 'lazy'

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: /media/cache

    filter_sets:
      images_galery:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [350, 800]
            mode: outbound

      images_architecture_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [700, 900]
            mode: inset

      image_home_tudeils:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [1024, 730]
            mode: outbound

      images_design_texture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [250, 500]
            mode: inset

      images_design_plan:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [400, 500]
            mode: outbound

      images_design_picture:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [1300, 750]
            mode: inset

      images_design_cover:
        cache: default
        quality: 100
        filters:
          auto_rotate: ~
          strip: ~
          thumbnail:
            size: [500, 500] # Tamaño cuadrado para ajustarse al contenedor
            mode: outbound       # Puedes usar 'inset' para asegurar que se recorte y ajuste bien

      cache: ~