symfonycasts_sass:
  root_sass:
    - 'assets/styles/app.scss'
    - 'assets/styles/home.scss'
    - 'assets/styles/design.scss'
    - 'assets/styles/architecture.scss'
    - 'assets/styles/illustration.scss'
    - 'assets/styles/pages/design/projects/bureauII.scss'