version: '3.2'

services: 

  database: 
    image: mysql:8.0.36
    container_name: juliette_database
    restart: always
    ports:
      - 7800:3306
    environment:
      MYSQL_ROOT_PASSWORD: juliette
      MYSQL_DATABASE: juliette
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: juliette_phpmyadmin
    ports: 
      - 7801:80
    depends_on:
      - database
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=juliette
      - PHP_INI_UPLOAD_MAX_FILESIZE=100M
      - PHP_INI_POST_MAX_SIZE=100M
      - UPLOAD_LIMIT=2048M
    restart: always

  mailer:
    image: mailhog/mailhog
    container_name: juliette_mailer
    ports: 
      - 7802:1025 # smtp server
      - 7803:8025 # web ui

volumes:
  database_data: 
